services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - /home/ubuntu/data/redis:/data
    networks:
      - main-net
    environment:
            TZ: 'Asia/Seoul'
    restart: unless-stopped

networks:
  main-net:
    external: true
