services:
  mmmm-api-blue:
    container_name: mmmm-api-blue
    image: thispear/mmmm:latest
    restart: always
    ports:
      - '8081:8081'
   
    environment:
      TZ: 'Asia/Seoul'
      SPRING_PROFILES_ACTIVE: 'prod'
      SERVER_PORT: '8081'
      TEST_DB_URL: 'jdbc:postgresql://mmmm-testgres-1:5432/test?currentSchema=public'
      TEST_DB_USERNAME: ''
      TEST_DB_PASSWORD: ''
      DB_URL: 'jdbc:postgresql://postgres:5432/minimoneymanymo?currentSchema=public'
      DB_USERNAME: ''
      DB_PASSWORD: ''
      ADMIN_PWD: ''
      JWT_SECRET: 'The quick brown fox jumps over the lazy dog while the vibrant sky turns shades of purple and orange. In the middle of the forest, a whimsical unicorn with a rainbow mane prances around, leaving sparkles in its wake. Nearby, a group of squirrels play a tiny piano, each note echoing through the trees. A mysterious owl watches from above, its eyes glowing with wisdom. The river flows gently, carrying leaves and whispers of forgotten tales. Bubbles rise from the depths, bursting with laughter and secrets untold. This surreal landscape blends reality with dreams, creating a tapestry of endless wonder.'
      JWT_ACCESS_TOKEN_EXPIRATION: '360000'
      JWT_REFRESH_TOKEN_EXPIRATION: '604800000'
      UPLOAD_IMAGE_DIR: ''
      UPLOAD_VIDEO_DIR: ''
      FILE_SERVER_URL: ''
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'
      AWS_ACCESS_KEY: ''
      AWS_SECRET_KEY: ''
      AWS_BUCKET_NAME: 'teamcook-bucket'
      KOREA_INVESTMENT_API_URL: ''
      KOREA_INVESTMENT_API_APPKEY: ''
      KOREA_INVESTMENT_API_APPSECRET: ''
      SHINHAN_API_URL: ''
      SHINHAN_API_APPKEY: ''
      SHINHAN_API_APPSECRET: ''
      DEEPSEARCH_API_URL: ''
      GPT_API_URL: ''
      GPT_API_KEY: ''
    networks:
            - main-net
                    

networks:
        main-net:
                external: true  
